/**
 * @author Marcos Barrios
 * @since 24_10_2023
 * @desc Build a time table
 */

'use strict';

import GoogleTrendsScrapper from "../../routes/google-trends-scrapper.mjs";

import { inspect } from 'util';

export default async function addInterest() {
  const searchTerms = [
    'foo',
    'rafa nadal',
    'roger federer',
    'naranja',
    'manzana',
    'xbox',
    'playstation',
    'unity',
    'unreal engine',
    'amazon stocks',
    'lunar eclipse',
    'machine learning',
    'underwater basket weaving',
    'ancient civilizations',
    'quantum physics',
    'chocolate recipes',
    'urban gardening',
    'virtual reality',
    'time travel',
    'coffee brewing techniques',
    'astrobiology',
    'ancient philosophy',
    'robotics',
    'creative writing prompts',
    'sustainable living',
    'astronomy',
    'mindfulness meditation',
    'cryptocurrency',
    'DIY home improvement',
    'epic fantasy books',
    'healthy smoothie recipes',
    'artificial intelligence',
    'ancient architecture',
    'historical mysteries',
    'space exploration',
    'comic book heroes',
    'culinary arts',
    'futuristic technology',
    'ancient art',
    'mind-bending movies',
    'oceanography',
    'computer programming',
    'philosophical paradoxes',
    'medieval history',
    'cryptic crossword puzzles',
    'DIY electronics projects',
    'theoretical physics',
    'world mythology',
    '3D printing',
    'ancient languages',
    'creative photography',
    'urban legends',
    'biohacking',
    'psychology experiments',
    'indie video games',
    'paleontology',
    'Japanese tea ceremonies',
    'climate change',
    'mind-expanding books',
    'ancient medicine',
    'virtual art galleries',
    'DIY fashion',
    'the nature of consciousness',
    'historical fashion',
    'ancient astronomy',
    'cybersecurity',
    'alternative energy sources',
    'time-lapse photography',
    'nanotechnology',
    'DIY woodworking projects',
    'ancient music',
    'mindfulness practices',
    'ancient literature',
    'cryptic art',
    'quantum computing',
    'space tourism',
    'eco-friendly living',
    'urban exploration',
    'ancient mathematics',
    'alternative medicine',
    'the philosophy of science',
    'DIY home decor',
    'ancient technology',
    'bioengineering',
    'virtual cooking classes',
    'mind-blowing documentaries',
    'ancient philosophy',
    'DIY outdoor projects',
    'the search for extraterrestrial life',
    'historical fiction books',
    'the art of storytelling',
    'astronomical phenomena',
    'cryptocurrency investing',
    'DIY gardening hacks',
    'ancient philosophy',
    'mindful eating',
    'ancient poetry',
    'robotic art installations',
    'cryptic poetry',
    'DIY health and wellness',
    'the physics of music',
    'ancient mythology',
    'mindfulness retreats',
    'virtual reality gaming',
    'eco-friendly fashion',
    'ancient wisdom traditions',
  ];

  // IMPORTANT: because first term is always 429, then pad the array and
  // put a trash search term as first element.

  const scrapper = new GoogleTrendsScrapper(searchTerms);
  const output = await scrapper.run();
  console.log(inspect(output));
}

addInterest();
